const StatesOptions = [
    { value: "Acre", key: "ACRE" },
    { value: "Alagoas", key: "ALAGOAS" },
    { value: "Amapá", key: "AMAPA" },
    { value: "Amazonas", key: "AMAZONAS" },
    { value: "Bahia", key: "BAHIA" },
    { value: "Ceará", key: "CEARA" },
    { value: "Distrito Federal", key: "DISTRITO_FEDERAL" },
    { value: "Espírito Santo", key: "ESPIRITO_SANTO" },
    { value: "Goiás", key: "GOIAS" },
    { value: "Maranhão", key: "MARANHAO" },
    { value: "Mato Grosso", key: "MATO_GROSSO" },
    { value: "Mato Grosso do Sul", key: "MATO_GROSSO_DO_SUL" },
    { value: "Minas Gerais", key: "MINAS_GERAIS" },
    { value: "Pará", key: "PARA" },
    { value: "Paraíba", key: "PARAIBA" },
    { value: "Paraná", key: "PARANA" },
    { value: "Pernambuco", key: "PERNAMBUCO" },
    { value: "Piauí", key: "PIAUI" },
    { value: "Rio de Janeiro", key: "RIO_DE_JANEIRO" },
    { value: "Rio Grande do Norte", key: "RIO_GRANDE_DO_NORTE" },
    { value: "Rio Grande do Sul", key: "RIO_GRANDE_DO_SUL" },
    { value: "Rondônia", key: "RONDONIA" },
    { value: "Roraima", key: "RORAIMA" },
    { value: "Santa Catarina", key: "SANTA_CATARINA" },
    { value: "São Paulo", key: "SAO_PAULO" },
    { value: "Sergipe", key: "SERGIPE" },
    { value: "Tocantins", key: "TOCANTINS" },
    ];
  
  export default StatesOptions;